### ISSUE TITLE
ShareManager crash on startup

### ISSUE THREAD

**Issue by aedahh** [Nelspike/ShareManager#1]
Hello, thank you for sharing this project source. I am looking for stock profolio source for reference and currently trying this source and ran into issue below.

When compile app and run (from older adt-20140702 or latest android-studio-ide-181.5056338) it crashed with error below. Any help is greatly appreciated. Thanks for looking into this issue.
 

    Process: share.manager.stock, PID: 3015
    java.lang.RuntimeException: Unable to start activity ComponentInfo{share.manager.stock/share.manager.stock.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2195)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at share.manager.stock.MainActivity.onCreate(MainActivity.java:38)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 

![share manager stopped](https://user-images.githubusercontent.com/2760221/47532025-1c6c7800-d864-11e8-80ad-8b4affba1d21.png)

**Comment by Misirlou** [comment]
I've dealt with this code before, this does not surprise me. @Nelspike is a really bad programmer
